# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liquid Galaxy
email: liquid-galaxy@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Rally point for the Liquid Galaxy community and the Open Source code
  we publish to help others get start.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liquidgalaxy.github.io" # the base hostname & protocol for your site
#twitter_username:  liquid-galaxy
github_username:  LiquidGalaxy

# Build settings
markdown: kramdown
